#!/usr/bin/env bash
mkdir -p dist
echo "build src/serialize.ls -> dist/serialize.js ..."
./node_modules/.bin/lsc -cb src/serialize.ls > dist/serialize.js
echo "minifying serialize.js ..."
./node_modules/.bin/uglifyjs dist/serialize.js > dist/serialize.min.js
