// Generated by LiveScript 1.3.1
(function(){
  var chainify;
  chainify = function(opt, proc){
    return new Promise(function(res, rej){
      var ref$, list, delay, len, ret, _;
      if (Array.isArray(opt)) {
        ref$ = [opt, 0], list = ref$[0], delay = ref$[1];
      } else {
        ref$ = [opt.list || [], opt.delay || 0], list = ref$[0], delay = ref$[1];
      }
      len = list.length;
      ret = {
        data: [],
        fail: []
      };
      _ = function(list){
        var item;
        item = list.splice(0, 1)[0];
        if (!item) {
          return res(ret);
        }
        return proc({
          item: item,
          percent: (list.length / len) * 100
        }).then(function(d){
          return ret.data.push({
            item: item,
            data: d
          });
        })['catch'](function(e){
          return ret.fail.push({
            item: item,
            error: e
          });
        })['finally'](function(){
          return setTimeout(function(){
            return _(list);
          }, delay) || 0;
        });
      };
      return _(list);
    });
  };
  if (typeof window != 'undefined' && window !== null) {
    window.chainify = chainify;
  }
  if (typeof module != 'undefined' && module !== null) {
    return module.exports = chainify;
  }
})();